$("#img1").on("click",function(){
  window.open("http://www.aquashipping.co.in/");
});
$("#img2").on("click",function(){
  window.open("BrandBuild.jpg");
});
$("#img3").on("click",function(){
  window.open("http://hardipshipping.com/");
});
$("#img4").on("click",function(){
  window.open("https://www.kohliwebdesign.com/");
});
$("#img5").on("click",function(){
  window.open("http://paragwealth.com/");
});
$("#img6").on("click",function(){
  window.open("webDes.jpg");
});
$("#img7").on("click",function(){
  window.open("webdev.jpg");
});
